/**
 * Theme Presets — 9 curated theme configurations
 * Each preset provides a complete visual identity:
 * colors, typography hints, layout defaults, and content style.
 */
import type { TemplateSettings, ThemeVariant } from "lib/redux/types";

export interface ThemePreset {
  id: ThemeVariant;
  name: string;
  description: string;
  emoji: string;
  preview: {
    primaryColor: string;
    secondaryColor: string;
    bgColor: string;
    textColor: string;
  };
  settings: Partial<TemplateSettings>;
}

export const themePresets: ThemePreset[] = [
  {
    id: "minimal",
    name: "Minimal",
    description: "Clean and understated — lets content speak",
    emoji: "◻️",
    preview: { primaryColor: "#18181b", secondaryColor: "#71717a", bgColor: "#ffffff", textColor: "#18181b" },
    settings: {
      design: {
        colors: {
          primary: "#18181b",
          text: "#18181b",
          background: "#ffffff",
          secondary: "#71717a",
          accent: "#18181b",
          muted: "#a1a1aa",
          link: "#3b82f6",
          sidebarBg: "#fafafa",
          sidebarText: "#18181b",
          headerBg: "#ffffff",
          headerText: "#18181b",
        },
        theme: "minimal",
        colorMode: "light",
        background: { type: "solid" },
        cardStyle: "none",
        borderStyle: "hairline",
        shadowLevel: "none",
        accentTreatment: "none",
        sectionDivider: "line",
        level: { type: "circle", icon: "none" },
      },
      typography: {
        body: { fontFamily: "Inter", fontSize: 10, lineHeight: 1.5 },
        heading: { fontFamily: "Inter", fontSize: 11, lineHeight: 1.2 },
        name: { fontFamily: "Inter", fontSize: 24, fontWeight: 600, textTransform: "none" },
        letterSpacing: 0,
      },
      layout: {
        columns: 1,
        sidebarWidth: 30,
        fullWidth: false,
        headerStyle: "left-aligned",
        main: ["summary", "experience", "education", "projects", "skills"],
        sidebar: [],
      },
      content: {
        bulletStyle: "dash",
        dateFormat: "month-year",
        datePlacement: "right",
        showPhoto: false,
        skillBarStyle: "chips",
        iconStyle: "outline",
      },
    },
  },
  {
    id: "modern",
    name: "Modern",
    description: "Sleek two-column with vibrant accent colors",
    emoji: "🔷",
    preview: { primaryColor: "#3b82f6", secondaryColor: "#8b5cf6", bgColor: "#ffffff", textColor: "#0f172a" },
    settings: {
      design: {
        colors: {
          primary: "#3b82f6",
          text: "#0f172a",
          background: "#ffffff",
          secondary: "#8b5cf6",
          accent: "#06b6d4",
          muted: "#64748b",
          link: "#3b82f6",
          sidebarBg: "#0f172a",
          sidebarText: "#f8fafc",
          headerBg: "#ffffff",
          headerText: "#0f172a",
        },
        theme: "modern",
        colorMode: "light",
        background: { type: "solid" },
        cardStyle: "rounded",
        borderStyle: "none",
        shadowLevel: "soft",
        accentTreatment: "underline",
        sectionDivider: "gradient",
        level: { type: "progress-bar", icon: "none" },
      },
      typography: {
        body: { fontFamily: "Inter", fontSize: 11, lineHeight: 1.5 },
        heading: { fontFamily: "Poppins", fontSize: 13, lineHeight: 1.3 },
        name: { fontFamily: "Poppins", fontSize: 30, fontWeight: 700, textTransform: "none" },
        letterSpacing: 0,
      },
      layout: {
        columns: 2,
        sidebarWidth: 32,
        sidebarPosition: "left",
        fullWidth: false,
        headerStyle: "left-aligned",
        main: ["summary", "experience", "education", "projects"],
        sidebar: ["skills", "languages", "certifications"],
      },
      content: {
        bulletStyle: "circle",
        dateFormat: "month-year",
        datePlacement: "right",
        showPhoto: false,
        skillBarStyle: "bar",
        iconStyle: "filled",
      },
    },
  },
  {
    id: "classic",
    name: "Classic",
    description: "Traditional and timeless — perfect for corporate",
    emoji: "📜",
    preview: { primaryColor: "#1e3a5f", secondaryColor: "#2563eb", bgColor: "#ffffff", textColor: "#1e293b" },
    settings: {
      design: {
        colors: {
          primary: "#1e3a5f",
          text: "#1e293b",
          background: "#ffffff",
          secondary: "#2563eb",
          accent: "#1e3a5f",
          muted: "#94a3b8",
          link: "#2563eb",
          sidebarBg: "#f1f5f9",
          sidebarText: "#1e293b",
          headerBg: "#ffffff",
          headerText: "#1e3a5f",
        },
        theme: "classic",
        colorMode: "light",
        background: { type: "solid" },
        cardStyle: "none",
        borderStyle: "hairline",
        shadowLevel: "none",
        accentTreatment: "header-bar",
        sectionDivider: "double-line",
        level: { type: "circle", icon: "none" },
      },
      typography: {
        body: { fontFamily: "Times New Roman", fontSize: 11, lineHeight: 1.5 },
        heading: { fontFamily: "Georgia", fontSize: 13, lineHeight: 1.3 },
        name: { fontFamily: "Georgia", fontSize: 26, fontWeight: 700, textTransform: "uppercase" },
        letterSpacing: 1,
      },
      layout: {
        columns: 1,
        sidebarWidth: 30,
        fullWidth: false,
        headerStyle: "centered",
        main: ["summary", "experience", "education", "skills", "projects"],
        sidebar: [],
      },
      content: {
        bulletStyle: "circle",
        dateFormat: "month-year",
        datePlacement: "right",
        showPhoto: false,
        skillBarStyle: "chips",
        iconStyle: "outline",
      },
    },
  },
  {
    id: "creative",
    name: "Creative",
    description: "Bold colors and playful layout for designers",
    emoji: "🎨",
    preview: { primaryColor: "#ec4899", secondaryColor: "#f97316", bgColor: "#fdf2f8", textColor: "#1e1b4b" },
    settings: {
      design: {
        colors: {
          primary: "#ec4899",
          text: "#1e1b4b",
          background: "#fdf2f8",
          secondary: "#f97316",
          accent: "#8b5cf6",
          muted: "#a78bfa",
          link: "#ec4899",
          sidebarBg: "#1e1b4b",
          sidebarText: "#fce7f3",
          headerBg: "#fdf2f8",
          headerText: "#1e1b4b",
        },
        theme: "creative",
        colorMode: "light",
        background: { type: "gradient", gradient: "linear-gradient(135deg, #fdf2f8, #faf5ff)" },
        cardStyle: "elevated",
        borderStyle: "none",
        shadowLevel: "medium",
        accentTreatment: "corner-badge",
        sectionDivider: "gradient",
        level: { type: "progress-bar", icon: "none" },
      },
      typography: {
        body: { fontFamily: "Nunito", fontSize: 11, lineHeight: 1.6 },
        heading: { fontFamily: "Outfit", fontSize: 14, lineHeight: 1.3 },
        name: { fontFamily: "Outfit", fontSize: 34, fontWeight: 800, textTransform: "none" },
        letterSpacing: -0.5,
      },
      layout: {
        columns: 2,
        sidebarWidth: 35,
        sidebarPosition: "left",
        fullWidth: false,
        headerStyle: "banner",
        main: ["summary", "experience", "projects"],
        sidebar: ["skills", "education", "languages", "certifications"],
      },
      content: {
        bulletStyle: "arrow",
        dateFormat: "month-year",
        datePlacement: "below",
        showPhoto: true,
        photoShape: "circle",
        photoSize: 100,
        skillBarStyle: "bar",
        iconStyle: "duotone",
      },
    },
  },
  {
    id: "corporate",
    name: "Corporate",
    description: "Professional and structured for business roles",
    emoji: "🏢",
    preview: { primaryColor: "#0f4c81", secondaryColor: "#2d6a9f", bgColor: "#ffffff", textColor: "#1a202c" },
    settings: {
      design: {
        colors: {
          primary: "#0f4c81",
          text: "#1a202c",
          background: "#ffffff",
          secondary: "#2d6a9f",
          accent: "#0f4c81",
          muted: "#718096",
          link: "#2d6a9f",
          sidebarBg: "#f7fafc",
          sidebarText: "#1a202c",
          headerBg: "#0f4c81",
          headerText: "#ffffff",
        },
        theme: "corporate",
        colorMode: "light",
        background: { type: "solid" },
        cardStyle: "boxed",
        borderStyle: "hairline",
        shadowLevel: "soft",
        accentTreatment: "header-bar",
        sectionDivider: "line",
        level: { type: "rectangle", icon: "none" },
      },
      typography: {
        body: { fontFamily: "Calibri", fontSize: 11, lineHeight: 1.5 },
        heading: { fontFamily: "Calibri", fontSize: 13, lineHeight: 1.3 },
        name: { fontFamily: "Calibri", fontSize: 26, fontWeight: 700, textTransform: "uppercase" },
        letterSpacing: 0.5,
      },
      layout: {
        columns: 1,
        sidebarWidth: 30,
        fullWidth: false,
        headerStyle: "banner",
        main: ["summary", "experience", "education", "skills", "certifications"],
        sidebar: [],
      },
      content: {
        bulletStyle: "square",
        dateFormat: "month-year",
        datePlacement: "right",
        showPhoto: false,
        skillBarStyle: "chips",
        iconStyle: "filled",
      },
    },
  },
  {
    id: "executive",
    name: "Executive",
    description: "Premium elegance for senior leadership",
    emoji: "👔",
    preview: { primaryColor: "#1a1a2e", secondaryColor: "#c9a96e", bgColor: "#fefefe", textColor: "#1a1a2e" },
    settings: {
      design: {
        colors: {
          primary: "#1a1a2e",
          text: "#1a1a2e",
          background: "#fefefe",
          secondary: "#c9a96e",
          accent: "#c9a96e",
          muted: "#8b8b8b",
          link: "#c9a96e",
          sidebarBg: "#1a1a2e",
          sidebarText: "#e8dcc8",
          headerBg: "#1a1a2e",
          headerText: "#e8dcc8",
        },
        theme: "executive",
        colorMode: "light",
        background: { type: "solid" },
        cardStyle: "ghost",
        borderStyle: "hairline",
        shadowLevel: "none",
        accentTreatment: "sidebar-bar",
        sectionDivider: "line",
        level: { type: "circle", icon: "none" },
      },
      typography: {
        body: { fontFamily: "Garamond", fontSize: 11, lineHeight: 1.6 },
        heading: { fontFamily: "Playfair Display", fontSize: 14, lineHeight: 1.2 },
        name: { fontFamily: "Playfair Display", fontSize: 32, fontWeight: 700, textTransform: "none" },
        letterSpacing: 0.5,
        fontFeatures: { smallCaps: true, ligatures: true },
      },
      layout: {
        columns: 1,
        sidebarWidth: 30,
        fullWidth: false,
        headerStyle: "centered",
        main: ["summary", "experience", "education", "skills", "awards"],
        sidebar: [],
      },
      content: {
        bulletStyle: "dash",
        dateFormat: "month-year",
        datePlacement: "right",
        showPhoto: false,
        skillBarStyle: "chips",
        iconStyle: "outline",
        emphasisRules: { boldRole: true, italicOrg: true, highlightMetrics: true },
      },
    },
  },
  {
    id: "academic",
    name: "Academic",
    description: "Scholarly layout for researchers and educators",
    emoji: "🎓",
    preview: { primaryColor: "#7c2d12", secondaryColor: "#dc2626", bgColor: "#fffbf5", textColor: "#292524" },
    settings: {
      design: {
        colors: {
          primary: "#7c2d12",
          text: "#292524",
          background: "#fffbf5",
          secondary: "#dc2626",
          accent: "#7c2d12",
          muted: "#78716c",
          link: "#dc2626",
          sidebarBg: "#fef3c7",
          sidebarText: "#292524",
          headerBg: "#fffbf5",
          headerText: "#7c2d12",
        },
        theme: "academic",
        colorMode: "light",
        background: { type: "solid" },
        cardStyle: "none",
        borderStyle: "hairline",
        shadowLevel: "none",
        accentTreatment: "underline",
        sectionDivider: "double-line",
        level: { type: "circle", icon: "none" },
      },
      typography: {
        body: { fontFamily: "Lora", fontSize: 11, lineHeight: 1.6 },
        heading: { fontFamily: "Merriweather", fontSize: 13, lineHeight: 1.3 },
        name: { fontFamily: "Merriweather", fontSize: 24, fontWeight: 700, textTransform: "none" },
        letterSpacing: 0,
        fontFeatures: { ligatures: true, oldstyleFigures: true },
      },
      layout: {
        columns: 1,
        sidebarWidth: 30,
        fullWidth: false,
        headerStyle: "left-aligned",
        main: ["summary", "experience", "education", "publications", "skills", "awards"],
        sidebar: [],
      },
      content: {
        bulletStyle: "circle",
        dateFormat: "yyyy",
        datePlacement: "right",
        showPhoto: false,
        skillBarStyle: "chips",
        iconStyle: "outline",
      },
    },
  },
  {
    id: "infographic",
    name: "Infographic",
    description: "Data-rich visual resume with charts and icons",
    emoji: "📊",
    preview: { primaryColor: "#6366f1", secondaryColor: "#06b6d4", bgColor: "#f8fafc", textColor: "#1e293b" },
    settings: {
      design: {
        colors: {
          primary: "#6366f1",
          text: "#1e293b",
          background: "#f8fafc",
          secondary: "#06b6d4",
          accent: "#f59e0b",
          muted: "#94a3b8",
          link: "#6366f1",
          sidebarBg: "#1e293b",
          sidebarText: "#e2e8f0",
          headerBg: "#6366f1",
          headerText: "#ffffff",
        },
        theme: "infographic",
        colorMode: "light",
        background: { type: "gradient", gradient: "linear-gradient(180deg, #f8fafc, #e2e8f0)" },
        cardStyle: "rounded",
        borderStyle: "none",
        shadowLevel: "medium",
        accentTreatment: "corner-badge",
        sectionDivider: "none",
        level: { type: "progress-bar", icon: "none" },
      },
      typography: {
        body: { fontFamily: "Nunito", fontSize: 10, lineHeight: 1.5 },
        heading: { fontFamily: "Montserrat", fontSize: 12, lineHeight: 1.3 },
        name: { fontFamily: "Montserrat", fontSize: 28, fontWeight: 800, textTransform: "none" },
        letterSpacing: 0,
      },
      layout: {
        columns: 2,
        sidebarWidth: 35,
        sidebarPosition: "left",
        fullWidth: false,
        headerStyle: "banner",
        main: ["summary", "experience", "projects"],
        sidebar: ["skills", "education", "languages", "certifications"],
      },
      content: {
        bulletStyle: "checkmark",
        dateFormat: "duration",
        datePlacement: "inline",
        showPhoto: true,
        photoShape: "circle",
        photoSize: 120,
        showSkillBars: true,
        skillBarStyle: "bar",
        showIcons: true,
        iconStyle: "filled",
      },
    },
  },
  {
    id: "portfolio-first",
    name: "Portfolio",
    description: "Project-forward layout for developers and creatives",
    emoji: "💼",
    preview: { primaryColor: "#10b981", secondaryColor: "#6ee7b7", bgColor: "#0f172a", textColor: "#f8fafc" },
    settings: {
      design: {
        colors: {
          primary: "#10b981",
          text: "#0f172a",
          background: "#ffffff",
          secondary: "#6ee7b7",
          accent: "#10b981",
          muted: "#64748b",
          link: "#10b981",
          sidebarBg: "#0f172a",
          sidebarText: "#f8fafc",
          headerBg: "#0f172a",
          headerText: "#f8fafc",
        },
        theme: "portfolio-first",
        colorMode: "light",
        background: { type: "solid" },
        cardStyle: "elevated",
        borderStyle: "none",
        shadowLevel: "soft",
        accentTreatment: "sidebar-bar",
        sectionDivider: "gradient",
        level: { type: "progress-bar", icon: "none" },
      },
      typography: {
        body: { fontFamily: "Space Grotesk", fontSize: 11, lineHeight: 1.5 },
        heading: { fontFamily: "Space Grotesk", fontSize: 14, lineHeight: 1.2 },
        name: { fontFamily: "Space Grotesk", fontSize: 30, fontWeight: 700, textTransform: "none" },
        letterSpacing: -0.5,
      },
      layout: {
        columns: 2,
        sidebarWidth: 30,
        sidebarPosition: "right",
        fullWidth: false,
        headerStyle: "banner",
        main: ["projects", "experience"],
        sidebar: ["summary", "skills", "education", "languages"],
      },
      content: {
        bulletStyle: "arrow",
        dateFormat: "month-year",
        datePlacement: "right",
        showPhoto: false,
        skillBarStyle: "bar",
        iconStyle: "duotone",
      },
    },
  },
];

// Helper to get a preset by ID
export const getPresetById = (id: ThemeVariant): ThemePreset | undefined =>
  themePresets.find((p) => p.id === id);

// Get all preset IDs
export const presetIds = themePresets.map((p) => p.id);
