export const reactiveResumeTemplates = [
  {
    id: "reactive-onyx",
    name: "Onyx",
    color: "#1a1a2e",
    description: "A sleek, dark-themed template with clean typography",
    category: "professional" as const,
  },
  {
    id: "reactive-pikachu",
    name: "Pikachu",
    color: "#ffd700",
    description: "Bold yellow accents with energetic design",
    category: "creative" as const,
  },
  {
    id: "reactive-azurill",
    name: "Azurill",
    color: "#87ceeb",
    description: "Soft blue tones for a friendly appearance",
    category: "minimal" as const,
  },
  {
    id: "reactive-bronzor",
    name: "Bronzor",
    color: "#7c7c7c",
    description: "Metallic gray with structured layout",
    category: "professional" as const,
  },
  {
    id: "reactive-chikorita",
    name: "Chikorita",
    color: "#98fb98",
    description: "Fresh green accents, nature-inspired",
    category: "creative" as const,
  },
  {
    id: "reactive-ditgar",
    name: "Ditgar",
    color: "#dc143c",
    description: "Bold crimson for strong visual impact",
    category: "creative" as const,
  },
  {
    id: "reactive-ditto",
    name: "Ditto",
    color: "#9370db",
    description: "Purple tones, versatile and adaptable",
    category: "modern" as const,
  },
  {
    id: "reactive-gengar",
    name: "Gengar",
    color: "#4b0082",
    description: "Deep purple, mysterious and elegant",
    category: "creative" as const,
  },
  {
    id: "reactive-glalie",
    name: "Glalie",
    color: "#4682b4",
    description: "Ice blue, cool and professional",
    category: "professional" as const,
  },
  {
    id: "reactive-kakuna",
    name: "Kakuna",
    color: "#deb887",
    description: "Warm beige tones, approachable",
    category: "minimal" as const,
  },
  {
    id: "reactive-lapras",
    name: "Lapras",
    color: "#5f9ea0",
    description: "Teal oceanic feel, calm and organized",
    category: "professional" as const,
  },
  {
    id: "reactive-leafish",
    name: "Leafish",
    color: "#228b22",
    description: "Forest green, earthy and reliable",
    category: "professional" as const,
  },
  {
    id: "reactive-meowth",
    name: "Meowth",
    color: "#ffdab9",
    description: "Warm peach tones, friendly and inviting",
    category: "creative" as const,
  },
  {
    id: "reactive-rhyhorn",
    name: "Rhyhorn",
    color: "#8b4513",
    description: "Brown earth tones, solid and dependable",
    category: "professional" as const,
  },
];
