import type { ImpactCVThemeConfig } from "./adapters";

export const impactCVThemes: ImpactCVThemeConfig[] = [
  {
    id: "impactcv-basic",
    name: "Basic",
    color: "text-gray-700",
    fontClass: "font-sans",
    spacing: "p-4",
    headerStyle: "text-2xl font-semibold",
    sectionTitleStyle: "text-lg font-semibold uppercase tracking-wide text-gray-700 border-b border-gray-200 pb-1 mb-3",
    sectionContentStyle: "mt-2",
    category: "minimal",
  },
  {
    id: "impactcv-casual",
    name: "Casual",
    color: "text-green-500",
    fontClass: "font-sans",
    spacing: "p-5",
    headerStyle: "text-3xl font-bold",
    sectionTitleStyle: "text-xl font-medium text-green-500 mb-3",
    sectionContentStyle: "mt-3",
    category: "creative",
  },
  {
    id: "impactcv-professional",
    name: "Professional",
    color: "text-blue-500",
    fontClass: "font-serif",
    spacing: "p-6",
    headerStyle: "text-2xl font-bold tracking-tight text-blue-500 border-b-2 border-blue-500 pb-2",
    sectionTitleStyle: "text-base uppercase font-bold tracking-widest bg-blue-500 text-white py-1 px-3 inline-block mb-3",
    sectionContentStyle: "mt-3 pl-3 border-l-2 border-blue-500/30",
    backgroundClass: "bg-white",
    cardStyle: "p-6 rounded-none shadow-md",
    borderStyle: "border-t-8 border-blue-500",
    imagePlacement: "right",
    imageStyle: "w-28 h-28 rounded-none shadow-md border-4 border-white",
    category: "professional",
  },
  {
    id: "impactcv-creative",
    name: "Creative",
    color: "text-pink-500",
    fontClass: "font-sans",
    spacing: "space-y-8",
    headerStyle: "text-4xl font-black italic text-transparent bg-clip-text bg-gradient-to-r from-pink-500 to-pink-500",
    sectionTitleStyle: "text-lg font-bold text-pink-500 relative pl-10 mb-4 before:content-[''] before:absolute before:left-0 before:top-1/2 before:-translate-y-1/2 before:w-8 before:h-[3px] before:bg-pink-500",
    sectionContentStyle: "mt-4 p-4 rounded-lg bg-pink-50/50",
    backgroundClass: "bg-gradient-to-br from-white to-pink-50",
    cardStyle: "p-8 rounded-3xl shadow-xl",
    imagePlacement: "top",
    imageStyle: "w-40 h-40 mx-auto rounded-full border-8 border-white shadow-lg transform -rotate-6",
    category: "creative",
  },
  {
    id: "impactcv-modern",
    name: "Modern",
    color: "text-purple-600",
    fontClass: "font-sans",
    spacing: "space-y-7",
    headerStyle: "text-3xl font-extrabold tracking-tight text-purple-600 flex flex-col items-center",
    sectionTitleStyle: "text-sm font-semibold uppercase tracking-widest text-purple-600/80 flex items-center after:content-[''] after:ml-2 after:flex-1 after:h-px after:bg-purple-600/30",
    sectionContentStyle: "mt-4 grid grid-cols-1 gap-4",
    backgroundClass: "bg-white",
    cardStyle: "p-7 shadow-lg rounded-xl",
    imagePlacement: "center",
    imageStyle: "w-32 h-32 mx-auto rounded-full mb-4 ring-4 ring-purple-600/20 ring-offset-4",
    category: "modern",
  },
  {
    id: "impactcv-business",
    name: "Business",
    color: "text-orange-500",
    fontClass: "font-serif",
    spacing: "space-y-5",
    headerStyle: "text-3xl font-semibold text-orange-500 flex items-end gap-4 border-b-2 border-orange-500 pb-2",
    sectionTitleStyle: "text-lg font-semibold text-white bg-orange-500 py-1 px-3 rounded-sm inline-block mb-3 shadow-sm",
    sectionContentStyle: "mt-4 px-3",
    backgroundClass: "bg-amber-50/50",
    cardStyle: "p-6 rounded-md border border-amber-100 shadow-md",
    imagePlacement: "left",
    imageStyle: "w-28 h-28 rounded-md border-2 border-amber-200 shadow-md mr-4",
    category: "professional",
  },
  {
    id: "impactcv-minimal",
    name: "Minimal",
    color: "text-slate-800",
    fontClass: "font-sans",
    spacing: "space-y-5",
    headerStyle: "text-3xl font-light tracking-tight",
    sectionTitleStyle: "text-sm font-medium uppercase tracking-widest text-slate-500 mb-3",
    sectionContentStyle: "mt-2",
    backgroundClass: "bg-white",
    cardStyle: "p-5",
    imagePlacement: "top",
    imageStyle: "w-24 h-24 mx-auto rounded-full mb-4 border border-slate-200 shadow-sm",
    category: "minimal",
  },
  {
    id: "impactcv-elegant",
    name: "Elegant",
    color: "text-emerald-700",
    fontClass: "font-serif",
    spacing: "space-y-6",
    headerStyle: "text-4xl font-light tracking-wide text-emerald-800",
    sectionTitleStyle: "text-lg italic font-normal text-emerald-700 border-b border-emerald-200 pb-1 mb-3",
    sectionContentStyle: "mt-4 text-gray-700",
    backgroundClass: "bg-emerald-50",
    cardStyle: "p-6 border-l-4 border-emerald-700",
    imagePlacement: "left",
    imageStyle: "w-32 h-32 rounded-md mr-6 float-left shadow-md",
    category: "professional",
  },
  {
    id: "impactcv-technical",
    name: "Technical",
    color: "text-sky-700",
    fontClass: "font-mono",
    spacing: "space-y-5",
    headerStyle: "text-2xl font-bold tracking-tight text-sky-700",
    sectionTitleStyle: "text-base font-bold bg-sky-100 text-sky-700 px-2 py-1 rounded mb-3 inline-block",
    sectionContentStyle: "mt-3 text-gray-800 space-y-2",
    backgroundClass: "bg-gray-50",
    cardStyle: "p-4 border border-sky-200 rounded-md",
    imagePlacement: "right",
    imageStyle: "w-24 h-24 rounded float-right ml-4 border border-sky-200 p-1",
    category: "professional",
  },
  {
    id: "impactcv-vibrant",
    name: "Vibrant",
    color: "text-fuchsia-600",
    fontClass: "font-sans",
    spacing: "space-y-6",
    headerStyle: "text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-fuchsia-600 to-pink-600",
    sectionTitleStyle: "text-lg font-bold text-fuchsia-600 mb-2",
    sectionContentStyle: "mt-3 text-gray-700 border-l-4 border-pink-300 pl-4",
    backgroundClass: "bg-gradient-to-br from-white to-fuchsia-50",
    cardStyle: "p-5 rounded-lg shadow-md",
    imagePlacement: "top",
    imageStyle: "w-32 h-32 mx-auto rounded-full mb-4 border-4 border-white shadow-md",
    category: "creative",
  },
  {
    id: "impactcv-nordic",
    name: "Nordic",
    color: "text-slate-700",
    fontClass: "font-sans",
    spacing: "space-y-6",
    headerStyle: "text-2xl font-normal tracking-wide text-slate-800",
    sectionTitleStyle: "text-sm font-medium uppercase tracking-widest text-slate-600 pb-1 mb-4 border-b border-slate-200",
    sectionContentStyle: "mt-3 text-slate-700",
    backgroundClass: "bg-slate-50",
    cardStyle: "p-6 border border-slate-100 rounded-none",
    imagePlacement: "left",
    imageStyle: "w-28 h-28 rounded-none grayscale mr-5",
    category: "minimal",
  },
  {
    id: "impactcv-blueprint",
    name: "Blueprint",
    color: "text-blue-900",
    fontClass: "font-mono",
    spacing: "space-y-6",
    headerStyle: "text-2xl font-bold text-blue-900 mb-2",
    sectionTitleStyle: "text-sm font-bold uppercase tracking-widest text-blue-800 bg-blue-100 py-1 px-2 mb-3 inline-block",
    sectionContentStyle: "mt-3 ml-2 border-l-2 border-blue-200 pl-4",
    backgroundClass: "bg-blue-50",
    cardStyle: "p-6 border border-blue-200 rounded-md",
    imagePlacement: "right",
    imageStyle: "w-28 h-28 rounded border-2 border-blue-300 p-1 float-right ml-4",
    category: "professional",
  },
  {
    id: "impactcv-gradient",
    name: "Gradient",
    color: "text-indigo-600",
    fontClass: "font-sans",
    spacing: "space-y-7",
    headerStyle: "text-3xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 pb-2",
    sectionTitleStyle: "text-base font-bold bg-gradient-to-r from-indigo-500 to-purple-500 text-white px-3 py-1 rounded-full mb-3 inline-block shadow-sm",
    sectionContentStyle: "mt-3 bg-white/90 rounded-lg p-4 shadow-sm",
    backgroundClass: "bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50",
    cardStyle: "p-6 rounded-xl backdrop-blur-sm border border-white",
    imagePlacement: "center",
    imageStyle: "w-32 h-32 mx-auto rounded-full border-4 border-white shadow-lg mb-4 bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500 p-1",
    category: "modern",
  },
  {
    id: "impactcv-retro",
    name: "Retro",
    color: "text-amber-700",
    fontClass: "font-mono",
    spacing: "space-y-6",
    headerStyle: "text-3xl font-black uppercase text-amber-800 border-b-4 border-amber-500 pb-2",
    sectionTitleStyle: "text-lg font-bold uppercase bg-amber-200 text-amber-800 px-2 py-1 inline-block mb-3 border-2 border-amber-800",
    sectionContentStyle: "mt-3 border-2 border-amber-200 p-3",
    backgroundClass: "bg-amber-50",
    cardStyle: "p-6 border-4 border-double border-amber-300",
    imagePlacement: "left",
    imageStyle: "w-28 h-28 p-1 border-2 border-amber-700 mr-4 grayscale sepia",
    category: "creative",
  },
  {
    id: "impactcv-academic",
    name: "Academic",
    color: "text-indigo-800",
    fontClass: "font-serif",
    spacing: "space-y-7",
    headerStyle: "text-2xl font-bold text-center text-indigo-900",
    sectionTitleStyle: "text-lg font-semibold text-indigo-800 border-b-2 border-indigo-200 pb-1 mb-3",
    sectionContentStyle: "mt-4 text-gray-800",
    backgroundClass: "bg-indigo-50",
    cardStyle: "p-6 border border-indigo-100",
    imagePlacement: "center",
    imageStyle: "w-40 h-40 mx-auto rounded-md mb-4 border border-indigo-200 p-1",
    category: "academic",
  },
  {
    id: "impactcv-corporate",
    name: "Corporate",
    color: "text-gray-700",
    fontClass: "font-sans",
    spacing: "space-y-5",
    headerStyle: "text-2xl font-bold text-gray-800",
    sectionTitleStyle: "text-md font-bold text-gray-700 bg-gray-100 px-3 py-2 rounded mb-3 flex items-center",
    sectionContentStyle: "mt-4 text-gray-700 pl-3",
    backgroundClass: "bg-white",
    cardStyle: "p-6 border-b border-gray-200 shadow-sm",
    borderStyle: "border-l-4 border-gray-500",
    imagePlacement: "left",
    imageStyle: "w-28 h-28 rounded-md mr-5 float-left",
    category: "professional",
  },
  {
    id: "impactcv-artistic",
    name: "Artistic",
    color: "text-rose-600",
    fontClass: "font-sans",
    spacing: "space-y-6",
    headerStyle: "text-4xl font-black italic text-rose-600",
    sectionTitleStyle: "text-lg font-bold text-rose-500 inline-block relative after:content-[''] after:absolute after:w-full after:h-1 after:bg-rose-200 after:left-0 after:-bottom-1 mb-4",
    sectionContentStyle: "mt-4 text-gray-700",
    backgroundClass: "bg-rose-50",
    cardStyle: "p-8 rounded-lg",
    imagePlacement: "right",
    imageStyle: "w-40 h-40 rounded-full float-right ml-5 border-4 border-white shadow-lg transform -rotate-3",
    category: "creative",
  },
  {
    id: "impactcv-classic",
    name: "Classic",
    color: "text-stone-700",
    fontClass: "font-serif",
    spacing: "space-y-5",
    headerStyle: "text-3xl font-bold text-stone-800 text-center mb-2",
    sectionTitleStyle: "text-lg font-semibold text-stone-700 pb-1 mb-3 border-b border-stone-300",
    sectionContentStyle: "mt-3 text-stone-600",
    backgroundClass: "bg-stone-50",
    cardStyle: "p-6",
    borderStyle: "border-t-8 border-stone-300",
    imagePlacement: "center",
    imageStyle: "w-32 h-32 mx-auto rounded-full mb-3 grayscale",
    category: "professional",
  },
  {
    id: "impactcv-digital",
    name: "Digital",
    color: "text-cyan-600",
    fontClass: "font-sans",
    spacing: "space-y-6",
    headerStyle: "text-3xl font-bold text-cyan-700",
    sectionTitleStyle: "text-base font-medium text-white bg-gradient-to-r from-cyan-500 to-blue-500 px-3 py-1.5 rounded-md shadow-sm mb-3",
    sectionContentStyle: "mt-3 text-gray-700",
    backgroundClass: "bg-gradient-to-br from-white to-cyan-50",
    cardStyle: "p-5 rounded-xl shadow-sm border border-cyan-100",
    imagePlacement: "right",
    imageStyle: "w-28 h-28 float-right ml-4 rounded-lg ring-2 ring-cyan-200 shadow-sm p-1",
    category: "modern",
  },
  {
    id: "impactcv-futuristic",
    name: "Futuristic",
    color: "text-violet-600",
    fontClass: "font-sans",
    spacing: "space-y-7",
    headerStyle: "text-3xl font-extrabold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-violet-600 to-indigo-600",
    sectionTitleStyle: "text-sm font-bold uppercase tracking-widest text-violet-600 mb-2 flex items-center before:content-[''] before:block before:h-px before:w-5 before:mr-2 before:bg-gradient-to-r before:from-violet-400 before:to-indigo-400",
    sectionContentStyle: "mt-3 text-gray-700 bg-white/80 backdrop-blur-sm p-3 rounded-md",
    backgroundClass: "bg-gradient-to-br from-gray-100 via-white to-violet-50",
    cardStyle: "p-6 rounded-xl backdrop-blur-sm bg-white/20 border border-white/40 shadow-lg",
    imagePlacement: "center",
    imageStyle: "w-32 h-32 mx-auto rounded-xl mb-4 ring-2 ring-violet-200 shadow-lg p-1 backdrop-blur-sm bg-white/50",
    category: "modern",
  },
];
